use std::collections::HashMap;
use crate::ast::{Cmp,Expr,Stmt};
#[derive(Clone,Debug,PartialEq)] enum Value{Str(String),Num(i64),Bool(bool),Unit}
impl Value{fn truthy(&self)->bool{match self{Value::Bool(b)=>*b,Value::Num(n)=>*n!=0,Value::Str(s)=>!s.is_empty(),Value::Unit=>false}}}

type Functions=HashMap<String,(Vec<String>,Vec<Stmt>)>;
pub fn run(program:&[Stmt])->Result<(),String>{let mut funcs=Functions::new();for s in program{if let Stmt::Fn{name,params,body}=s{if funcs.insert(name.clone(),(params.clone(),body.clone())).is_some(){return Err(format!("duplicate function: {name}"))}}}let Some((params,body))=funcs.get("main").cloned()else{return Err("entry point 'main' not found".into())};if !params.is_empty(){return Err("main must not have parameters".into())}let mut env=HashMap::new();exec(&body,&mut env,&funcs)?;Ok(())}
fn exec(body:&[Stmt],env:&mut HashMap<String,Value>,funcs:&Functions)->Result<Option<Value>,String>{for s in body{match s{Stmt::Let(n,e)=>{let v=eval(e,env,funcs)?;env.insert(n.clone(),v);},Stmt::Print(e)=>println!("{}",display(&eval(e,env,funcs)?)),Stmt::Expr(e)=>{eval(e,env,funcs)?;},Stmt::Fn{..}=>{},Stmt::If{condition,then_body,else_body}=>{let b=if eval(condition,env,funcs)?.truthy(){then_body}else{else_body};if let Some(v)=exec(b,env,funcs)?{return Ok(Some(v))}},Stmt::While{condition,body:b}=>{while eval(condition,env,funcs)?.truthy(){if let Some(v)=exec(b,env,funcs)?{return Ok(Some(v))}}},Stmt::Return(e)=>return Ok(Some(match e{Some(x)=>eval(x,env,funcs)?,None=>Value::Unit}))}}Ok(None)}
fn eval(e:&Expr,env:&HashMap<String,Value>,funcs:&Functions)->Result<Value,String>{match e{Expr::Str(s)=>Ok(Value::Str(s.clone())),Expr::Num(n)=>Ok(Value::Num(*n)),Expr::Bool(b)=>Ok(Value::Bool(*b)),Expr::Var(n)=>env.get(n).cloned().ok_or_else(||format!("undefined variable: {n}")),Expr::Add(a,b)=>{let x=eval(a,env,funcs)?;let y=eval(b,env,funcs)?;match(x,y){(Value::Num(a),Value::Num(b))=>Ok(Value::Num(a+b)),(Value::Str(a),Value::Str(b))=>Ok(Value::Str(a+&b)),(a,b)=>Err(format!("cannot add {a:?} and {b:?}"))}},Expr::Sub(a,b)=>Ok(Value::Num(num(a,env,funcs)?.checked_sub(num(b,env,funcs)?).ok_or("integer overflow")?)),Expr::Mul(a,b)=>Ok(Value::Num(num(a,env,funcs)?.checked_mul(num(b,env,funcs)?).ok_or("integer overflow")?)),Expr::Div(a,b)=>{let y=num(b,env,funcs)?;if y==0{return Err("division by zero".into())}Ok(Value::Num(num(a,env,funcs)?.checked_div(y).ok_or("integer overflow")?))},Expr::Compare(a,c,b)=>{let x=eval(a,env,funcs)?;let y=eval(b,env,funcs)?;Ok(Value::Bool(match c{Cmp::Eq=>x==y,Cmp::Ne=>x!=y,Cmp::Lt=>ord(&x,&y,|o|o<0)?,Cmp::Le=>ord(&x,&y,|o|o<=0)?,Cmp::Gt=>ord(&x,&y,|o|o>0)?,Cmp::Ge=>ord(&x,&y,|o|o>=0)?}))},Expr::Call(n,args)=>{let(params,body)=funcs.get(n).ok_or_else(||format!("undefined function: {n}"))?.clone();if params.len()!=args.len(){return Err(format!("function {n} expects {}, got {}",params.len(),args.len()))}let mut local=HashMap::new();for(p,a)in params.iter().zip(args){local.insert(p.clone(),eval(a,env,funcs)?);}Ok(exec(&body,&mut local,funcs)?.unwrap_or(Value::Unit))}}}
fn num(e:&Expr,env:&HashMap<String,Value>,f:&Functions)->Result<i64,String>{match eval(e,env,f)?{Value::Num(n)=>Ok(n),v=>Err(format!("expected number, got {v:?}"))}}
fn ord(x:&Value,y:&Value,op:fn(i8)->bool)->Result<bool,String>{let o=match(x,y){(Value::Num(a),Value::Num(b))=>a.cmp(b)as i8,(Value::Str(a),Value::Str(b))=>a.cmp(b)as i8,_=>return Err("values are not comparable".into())};Ok(op(o))}
fn display(v:&Value)->String{match v{Value::Str(s)=>s.clone(),Value::Num(n)=>n.to_string(),Value::Bool(b)=>b.to_string(),Value::Unit=>"()".into()}}
