use std::collections::HashMap; use crate::ast::{Cmp,Expr,Stmt};
#[derive(Clone,Debug,PartialEq)] enum Value{Str(String),Num(i64),Bool(bool),Unit}
impl Value{fn truthy(&self)->bool{match self{Value::Bool(b)=>*b,Value::Num(n)=>*n!=0,Value::Str(s)=>!s.is_empty(),Value::Unit=>false}}}
pub fn run(program:&[Stmt])->Result<(),String>{let mut funcs=HashMap::new();for s in program{if let Stmt::Fn{name,params,body}=s{funcs.insert(name.clone(),(params.clone(),body.clone()));}}let mut env=HashMap::new();exec(program,&mut env,&funcs)?.1;Ok(())}
fn exec(body:&[Stmt],env:&mut HashMap<String,Value>,funcs:&HashMap<String,(Vec<String>,Vec<Stmt>)>)->Result<(Option<Value>,()),String>{for s in body{match s{Stmt::Let(n,e)=>{env.insert(n.clone(),eval(e,env,funcs)?);},Stmt::Print(e)=>println!("{}",display(&eval(e,env,funcs)?)),Stmt::Expr(e)=>{eval(e,env,funcs)?;},Stmt::Fn{..}=>{},Stmt::If{condition,then_body,else_body}=>{let b=if eval(condition,env,funcs)?.truthy(){then_body}else{else_body};if let Some(v)=exec(b,env,funcs)?.0{return Ok((Some(v),()))}},Stmt::While{condition,body:b}=>{while eval(condition,env,funcs)?.truthy(){if let Some(v)=exec(b,env,funcs)?.0{return Ok((Some(v),()))}}},Stmt::Return(e)=>return Ok((Some(match e{Some(x)=>eval(x,env,funcs)?,None=>Value::Unit}),()))}}Ok((None,()))}
fn eval(e:&Expr,env:&HashMap<String,Value>,funcs:&HashMap<String,(Vec<String>,Vec<Stmt>)>)->Result<Value,String>{match e{Expr::Str(s)=>Ok(Value::Str(s.clone())),Expr::Num(n)=>Ok(Value::Num(*n)),Expr::Bool(b)=>Ok(Value::Bool(*b)),Expr::Var(n)=>env.get(n).cloned().ok_or_else(||format!("undefined variable: {n}")),Expr::Add(a,b)=>bin_num_or_str(a,b,env,funcs,|x,y|x+y),Expr::Sub(a,b)=>bin_num(a,b,env,funcs,|x,y|x-y),Expr::Mul(a,b)=>bin_num(a,b,env,funcs,|x,y|x*y),Expr::Div(a,b)=>{let y=num(b,env,funcs)?;if y==0{return Err("division by zero".into())}Ok(Value::Num(num(a,env,funcs)?/y))},Expr::Compare(a,c,b)=>{let x=eval(a,env,funcs)?;let y=eval(b,env,funcs)?;let r=match c{Cmp::Eq=>x==y,Cmp::Ne=>x!=y,Cmp::Lt=>cmp(&x,&y,|a,b|a<b)?,Cmp::Le=>cmp(&x,&y,|a,b|a<=b)?,Cmp::Gt=>cmp(&x,&y,|a,b|a>b)?,Cmp::Ge=>cmp(&x,&y,|a,b|a>=b)?};Ok(Value::Bool(r))},Expr::Call(n,args)=>{let (params,body)=funcs.get(n).ok_or_else(||format!("undefined function: {n}"))?.clone();if params.len()!=args.len(){return Err(format!("function {n} expects {}, got {}",params.len(),args.len()))}let mut local=HashMap::new();for(p,a)in params.iter().zip(args){local.insert(p.clone(),eval(a,env,funcs)?);}Ok(exec(&body,&mut local,funcs)?.0.unwrap_or(Value::Unit))}}}
fn num(e:&Expr,env:&HashMap<String,Value>,f:&HashMap<String,(Vec<String>,Vec<Stmt>)>)->Result<i64,String>{match eval(e,env,f)?{Value::Num(n)=>Ok(n),v=>Err(format!("expected number, got {v:?}"))}}
fn bin_num(a:&Expr,b:&Expr,e:&HashMap<String,Value>,f:&HashMap<String,(Vec<String>,Vec<Stmt>)>,op:fn(i64,i64)->i64)->Result<Value,String>{Ok(Value::Num(op(num(a,e,f)?,num(b,e,f)?)))}
fn bin_num_or_str(a:&Expr,b:&Expr,e:&HashMap<String,Value>,f:&HashMap<String,(Vec<String>,Vec<Stmt>)>,op:fn(i64,i64)->i64)->Result<Value,String>{let x=eval(a,e,f)?;let y=eval(b,e,f)?;match(x,y){(Value::Num(a),Value::Num(b))=>Ok(Value::Num(op(a,b))),(Value::Str(a),Value::Str(b))=>Ok(Value::Str(a+&b)),(a,b)=>Err(format!("cannot add {a:?} and {b:?}"))}}
fn cmp(x:&Value,y:&Value,op:fn(i64,i64)->bool)->Result<bool,String>{match(x,y){(Value::Num(a),Value::Num(b))=>Ok(op(*a,*b)),(Value::Str(a),Value::Str(b))=>Ok(match op(1,2){true=>a<b,false=>a>=b}),_=>Err("values are not comparable".into())}}
fn display(v:&Value)->String{match v{Value::Str(s)=>s.clone(),Value::Num(n)=>n.to_string(),Value::Bool(b)=>b.to_string(),Value::Unit=>"()".into()}}
