name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check
      - run: cargo check --all-targets
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-targets
      - run: cargo build --release

      - name: Install maturin
        run: python3 -m pip install --disable-pip-version-check maturin==1.14.0

      - name: Build PyPI wheel
        run: maturin build --release --bindings bin --compatibility pypi

      - name: Build source distribution
        run: maturin sdist
